export const data = [
  {
    id: 'cld4mzboz00iisqaotef9s78n',
    title: 'Corsair RM Series, RM750, 750 Watt, 80+ Gold Certified, Fully Modular Power Supply, Microsoft Modern Standby',
    link: 'https://amazon.com/dp/B07RF237B1?tag=pcbuildcompat-20',
    img: 'https://m.media-amazon.com/images/I/51EkSdu6J-L._SL75_.jpg',
    price: 219,
    brand: 'Corsair',
    model: 'RM750',
    power: '750 W',
    color: 'Black',
    efficiency: '80+ Gold',
  },
  {
    id: 'cld4mzbp000issqaoxyjx5ffi',
    title: 'Corsair RM Series, RM850, 850 Watt, 80+ Gold Certified, Fully Modular Power Supply, Microsoft Modern Standby (CP-9020196-NA)',
    link: 'https://amazon.com/dp/B07RCKG95L?tag=pcbuildcompat-20',
    img: 'https://m.media-amazon.com/images/I/51SoQX-iCnL._SL75_.jpg',
    price: 214.99,
    brand: 'Corsair',
    model: 'RM850',
    power: '850 W',
    color: 'Black',
    efficiency: '80+ Gold',
  },
  {
    id: 'cld4mzbp000itsqaomib1tenu',
    title: 'Corsair CX Series 650 Watt 80 Plus Bronze Certified Modular Power Supply (CP-9020103-NA)',
    link: 'https://amazon.com/dp/B01B72W1VA?tag=pcbuildcompat-20',
    img: 'https://m.media-amazon.com/images/I/41h2NmpC0DL._SL75_.jpg',
    price: 179.99,
    brand: 'Corsair',
    model: 'CX 650',
    power: '650 W',
    color: 'Black',
    efficiency: '80+ Bronze',
  },
  {
    id: 'cld4mzbp000iusqaousczgc2j',
    title: 'EVGA 110-BQ-0500-K1, 500 Bq, 80+ Bronze 500W, Semi Modular, FDB Fan, 3 Year Warranty, Power Supply',
    link: 'https://amazon.com/dp/B01N3OAFHD?tag=pcbuildcompat-20',
    img: 'https://m.media-amazon.com/images/I/51fba2wglGL._SL75_.jpg',
    price: 98.99,
    brand: 'EVGA',
    model: 'BQ500',
    power: '500 W',
    color: 'Black',
    efficiency: '80+ Bronze',
  },
  {
    id: 'cld4mzbp000ivsqao19irja7n',
    title: 'Corsair CX Series 550 Watt 80 Plus Bronze Certified Modular Power Supply (CP-9020102-NA)',
    link: 'https://amazon.com/dp/B01B72W0A2?tag=pcbuildcompat-20',
    img: 'https://m.media-amazon.com/images/I/41O5gVNo3HL._SL75_.jpg',
    price: 179.99,
    brand: 'Corsair',
    model: 'CX',
    power: '550 W',
    color: 'Black',
    efficiency: '80+ Bronze',
  },
  {
    id: 'cld4mzbp000iwsqaodtb362va',
    title: 'EVGA 110-BQ-0600-K1 600 BQ, 80+ Bronze 600W, Semi Modular, FDB Fan, 3 Year Warranty, Power Supply',
    link: 'https://amazon.com/dp/B01MTJTO2O?tag=pcbuildcompat-20',
    img: 'https://m.media-amazon.com/images/I/51doGnle6SL._SL75_.jpg',
    price: 80,
    brand: 'EVGA',
    model: 'BQ',
    power: '600 W',
    color: 'Black',
    efficiency: '80+ Bronze',
  },
  {
    id: 'cld4mzbp000ixsqaoxhgjiyrz',
    title: 'EVGA 700 BR, 80+ Bronze 700W, 3 Year Warranty, Power Supply 100- BR-0700-K1 100-BR-0700-K1',
    link: 'https://amazon.com/dp/B07DTP6MWS?tag=pcbuildcompat-20',
    img: 'https://m.media-amazon.com/images/I/510bB5nKnuL._SL75_.jpg',
    price: 64.75,
    brand: 'EVGA',
    model: 'BR',
    power: '700 W',
    color: 'Black',
    efficiency: '80+ Bronze',
  },
  {
    id: 'cld4mzbp000iysqaodvac7bqn',
    title:
      'Corsair RMX Series, RM850x, 850 Watt, 80+ Gold Certified, Fully Modular Power Supply (Low Noise, Zero RPM Fan Mode, 105°C Capacitors, Fully Modular Cables, Compact Size) Black',
    link: 'https://amazon.com/dp/B079H5WNXN?tag=pcbuildcompat-20',
    img: 'https://m.media-amazon.com/images/I/51Ax0tT-ewL._SL75_.jpg',
    price: 214.99,
    brand: 'Corsair',
    model: 'RMx (2018)',
    power: '850 W',
    color: 'Black',
    efficiency: '80+ Gold',
  },
  {
    id: 'cld4mzbp000j6sqao1v0aiqg2',
    title: 'Corsair AXi Series, AX1600i, 1600 Watt, 80+ Titanium Certified, Fully Modular - Digital Power Supply (CP-9020087-NA)',
    link: 'https://amazon.com/dp/B0787G1Z74?tag=pcbuildcompat-20',
    img: 'https://m.media-amazon.com/images/I/41wkyzXvujL._SL75_.jpg',
    price: 622.99,
    brand: 'Corsair',
    model: 'AXi',
    power: '1600 W',
    color: 'Black',
    efficiency: '80+ Titanium',
  },
  {
    id: 'cld4mzbp000jqsqaoefwhrc8v',
    title: 'EVGA 100-BR-0500-K1 500 BR, 80+ Bronze 500W, 3 Year Warranty, Power Supply',
    link: 'https://amazon.com/dp/B07DTMXD83?tag=pcbuildcompat-20',
    img: 'https://m.media-amazon.com/images/I/51tJpLaiwUL._SL75_.jpg',
    price: 75.8,
    brand: 'EVGA',
    model: 'BR',
    power: '500 W',
    color: 'Black',
    efficiency: '80+ Bronze',
  },
]
